<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="jacroidEMF" nsURI="jacroidEMF" nsPrefix="jacroidEMF">
  <eAnnotations source="gmf"/>
  <eClassifiers xsi:type="ecore:EClass" name="Projeto">
    <eAnnotations source="gmf.diagram"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classes" upperBound="-1"
        eType="#//ClassesDescriptor" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="component" upperBound="-1"
        eType="#//Component" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enumerate" upperBound="-1"
        eType="#//Enumerate" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="firebaseAuth" eType="#//FirebaseAuth"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relationClasses" upperBound="-1"
        eType="#//RelationClassesDescriptor" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relationAttributeToComponent"
        upperBound="-1" eType="#//RelationAttributeDescriptorToComponent" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeDescriptor">
    <eAnnotations source="gmf.node">
      <details key="label" value="name, typeData"/>
      <details key="figure" value="rectangle"/>
      <details key="label.icon" value="false"/>
      <details key="label.pattern" value="{0} : {1}"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="classname" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="columnTable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="exhibitionName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="input" eType="#//Input"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isColumn" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="primaryKey" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="primaryKeyTable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeData" eType="#//TypeData"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassesDescriptor">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
      <details key="figure" value="rectangle"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tableName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//AttributeDescriptor" containment="true">
      <eAnnotations source="gmf.compartment">
        <details key="layout" value="list"/>
        <details key="collapsible" value="false"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Component">
    <eAnnotations source="gmf.node">
      <details key="label" value="name, type"/>
      <details key="figure" value="rectangle"/>
      <details key="label.pattern" value="{0} use {1}"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//Type"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FirebaseAuth">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
      <details key="figure" value="rectangle"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Enumerate">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
      <details key="figure" value="rectangle"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="item" upperBound="-1" eType="#//ItemEnum"
        containment="true">
      <eAnnotations source="gmf.compartment">
        <details key="layout" value="list"/>
        <details key="collapsible" value="false"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ItemEnum">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
      <details key="figure" value="rectangle"/>
      <details key="label.icon" value="false"/>
      <details key="label.pattern" value="{0}"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RelationClassesDescriptor">
    <eAnnotations source="gmf.link">
      <details key="source" value="source"/>
      <details key="target" value="target"/>
      <details key="target.decoration" value="arrow"/>
      <details key="style" value="solid"/>
      <details key="width" value="2"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//ClassesDescriptor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//ClassesDescriptor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RelationAttributeDescriptorToComponent">
    <eAnnotations source="gmf.link">
      <details key="source" value="source"/>
      <details key="target" value="target"/>
      <details key="target.decoration" value="arrow"/>
      <details key="style" value="dot"/>
      <details key="width" value="2"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//AttributeDescriptor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//Component"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TypeData">
    <eLiterals name="String"/>
    <eLiterals name="int" value="1"/>
    <eLiterals name="Long" value="2"/>
    <eLiterals name="Boolean" value="3"/>
    <eLiterals name="Enumerate" value="4"/>
    <eLiterals name="Image" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Type">
    <eLiterals name="none"/>
    <eLiterals name="GPS" value="1"/>
    <eLiterals name="CAMERA" value="2"/>
    <eLiterals name="NFC" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Input">
    <eLiterals name="select"/>
    <eLiterals name="text" value="1"/>
    <eLiterals name="checkbox" value="2"/>
    <eLiterals name="radiobutton" value="3"/>
    <eLiterals name="hidden" value="4"/>
    <eLiterals name="image" value="5"/>
  </eClassifiers>
</ecore:EPackage>
