/**
 */
package jacroidEMF.provider;

import jacroidEMF.util.JacroidEMFAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class JacroidEMFItemProviderAdapterFactory extends JacroidEMFAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public JacroidEMFItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link jacroidEMF.Projeto} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ProjetoItemProvider projetoItemProvider;

	/**
	 * This creates an adapter for a {@link jacroidEMF.Projeto}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createProjetoAdapter() {
		if (projetoItemProvider == null) {
			projetoItemProvider = new ProjetoItemProvider(this);
		}

		return projetoItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link jacroidEMF.AttributeDescriptor} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AttributeDescriptorItemProvider attributeDescriptorItemProvider;

	/**
	 * This creates an adapter for a {@link jacroidEMF.AttributeDescriptor}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAttributeDescriptorAdapter() {
		if (attributeDescriptorItemProvider == null) {
			attributeDescriptorItemProvider = new AttributeDescriptorItemProvider(this);
		}

		return attributeDescriptorItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link jacroidEMF.ClassesDescriptor} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ClassesDescriptorItemProvider classesDescriptorItemProvider;

	/**
	 * This creates an adapter for a {@link jacroidEMF.ClassesDescriptor}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createClassesDescriptorAdapter() {
		if (classesDescriptorItemProvider == null) {
			classesDescriptorItemProvider = new ClassesDescriptorItemProvider(this);
		}

		return classesDescriptorItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link jacroidEMF.Component} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComponentItemProvider componentItemProvider;

	/**
	 * This creates an adapter for a {@link jacroidEMF.Component}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createComponentAdapter() {
		if (componentItemProvider == null) {
			componentItemProvider = new ComponentItemProvider(this);
		}

		return componentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link jacroidEMF.FirebaseAuth} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FirebaseAuthItemProvider firebaseAuthItemProvider;

	/**
	 * This creates an adapter for a {@link jacroidEMF.FirebaseAuth}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFirebaseAuthAdapter() {
		if (firebaseAuthItemProvider == null) {
			firebaseAuthItemProvider = new FirebaseAuthItemProvider(this);
		}

		return firebaseAuthItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link jacroidEMF.Enumerate} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EnumerateItemProvider enumerateItemProvider;

	/**
	 * This creates an adapter for a {@link jacroidEMF.Enumerate}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEnumerateAdapter() {
		if (enumerateItemProvider == null) {
			enumerateItemProvider = new EnumerateItemProvider(this);
		}

		return enumerateItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link jacroidEMF.ItemEnum} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ItemEnumItemProvider itemEnumItemProvider;

	/**
	 * This creates an adapter for a {@link jacroidEMF.ItemEnum}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createItemEnumAdapter() {
		if (itemEnumItemProvider == null) {
			itemEnumItemProvider = new ItemEnumItemProvider(this);
		}

		return itemEnumItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link jacroidEMF.RelationClassesDescriptor} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RelationClassesDescriptorItemProvider relationClassesDescriptorItemProvider;

	/**
	 * This creates an adapter for a {@link jacroidEMF.RelationClassesDescriptor}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRelationClassesDescriptorAdapter() {
		if (relationClassesDescriptorItemProvider == null) {
			relationClassesDescriptorItemProvider = new RelationClassesDescriptorItemProvider(this);
		}

		return relationClassesDescriptorItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link jacroidEMF.RelationAttributeDescriptorToComponent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RelationAttributeDescriptorToComponentItemProvider relationAttributeDescriptorToComponentItemProvider;

	/**
	 * This creates an adapter for a {@link jacroidEMF.RelationAttributeDescriptorToComponent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRelationAttributeDescriptorToComponentAdapter() {
		if (relationAttributeDescriptorToComponentItemProvider == null) {
			relationAttributeDescriptorToComponentItemProvider = new RelationAttributeDescriptorToComponentItemProvider(this);
		}

		return relationAttributeDescriptorToComponentItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (projetoItemProvider != null) projetoItemProvider.dispose();
		if (attributeDescriptorItemProvider != null) attributeDescriptorItemProvider.dispose();
		if (classesDescriptorItemProvider != null) classesDescriptorItemProvider.dispose();
		if (componentItemProvider != null) componentItemProvider.dispose();
		if (firebaseAuthItemProvider != null) firebaseAuthItemProvider.dispose();
		if (enumerateItemProvider != null) enumerateItemProvider.dispose();
		if (itemEnumItemProvider != null) itemEnumItemProvider.dispose();
		if (relationClassesDescriptorItemProvider != null) relationClassesDescriptorItemProvider.dispose();
		if (relationAttributeDescriptorToComponentItemProvider != null) relationAttributeDescriptorToComponentItemProvider.dispose();
	}

}
